<?php

namespace EyadBereh\LaravelDbQueryLogger;

use EyadBereh\LaravelDbQueryLogger\Drivers\AbstractDriver;
use EyadBereh\LaravelDbQueryLogger\Interfaces\FileNameGeneratorInterface;
use EyadBereh\LaravelDbQueryLogger\Interfaces\MessageFormatterInterface;
use EyadBereh\LaravelDbQueryLogger\Interfaces\PathGeneratorInterface;
use EyadBereh\LaravelDbQueryLogger\Providers\EventServiceProvider;
use Spatie\LaravelPackageTools\Package;
use Spatie\LaravelPackageTools\PackageServiceProvider;

class LaravelDbQueryLoggerServiceProvider extends PackageServiceProvider
{
    public function registeringPackage()
    {
        parent::packageRegistered(); // TODO: Change the autogenerated stub
        $this->mergeConfigFrom(__DIR__.'/../config/db-query-logger.php', 'db-query-logger');
    }

    public function configurePackage(Package $package): void
    {
        /*
         * This class is a Package Service Provider
         *
         * More info: https://github.com/spatie/laravel-package-tools
         */
        $package
            ->name('laravel-db-query-logger')
            ->hasConfigFile('db-query-logger');

        $this->app->register(EventServiceProvider::class);
        $this->configureDriver();
        $this->configureFileNameGenerator();
        $this->configureMessageFormatter();
        $this->configurePathGenerator();
    }

    private function configureDriver(): void
    {
        $driver = config('db-query-logger.driver');
        $driver_info = config("db-query-logger.drivers.$driver");

        if (is_null($driver_info)) {
            throw new \Exception("Driver [$driver] not found.");
        }
        $concrete = $driver_info['concrete'];

        $reflection_class = new \ReflectionClass($concrete);

        if ($reflection_class->isAbstract()) {
            throw new \Exception("The specified logging driver [$concrete] must not be abstract");
        }

        if (! $reflection_class->isInstantiable()) {
            throw new \Exception("The specified logging driver [$concrete] must be instantiatable");
        }

        if (! $reflection_class->isSubclassOf(AbstractDriver::class)) {
            throw new \Exception("The specified logging driver [$concrete] must extend the class [".AbstractDriver::class.']');
        }

        if ($reflection_class->isAnonymous()) {
            throw new \Exception("The specified logging driver [$concrete] must not be anonymous");
        }

        $this->app->bind(AbstractDriver::class, $concrete);
    }

    private function configureFileNameGenerator(): void
    {
        $driver = config('db-query-logger.driver');
        $driver_info = config("db-query-logger.drivers.$driver");

        if (isset($driver_info['file_name'])) {
            $file_name_generator = $driver_info['file_name'];

            $reflection_class = new \ReflectionClass($file_name_generator);

            if ($reflection_class->isAbstract()) {
                throw new \Exception("The specified file name generator [$file_name_generator] must not be abstract");
            }

            if (! $reflection_class->isInstantiable()) {
                throw new \Exception("The specified file name generator [$file_name_generator] must be instantiatable");
            }

            if (! $reflection_class->implementsInterface(FileNameGeneratorInterface::class)) {
                throw new \Exception("The specified file name generator [$file_name_generator] must implement the interface [".FileNameGeneratorInterface::class.']');
            }

            if ($reflection_class->isAnonymous()) {
                throw new \Exception("The specified file name generator [$file_name_generator] must not be anonymous");
            }

            $this->app->bind(FileNameGeneratorInterface::class, $file_name_generator);
        }
    }

    private function configureMessageFormatter(): void
    {
        $driver = config('db-query-logger.driver');
        $driver_info = config("db-query-logger.drivers.$driver");

        if (isset($driver_info['message_formatter'])) {
            $message_formatter = $driver_info['message_formatter'];

            $reflection_class = new \ReflectionClass($message_formatter);

            if ($reflection_class->isAbstract()) {
                throw new \Exception("The specified message formatter [$message_formatter] must not be abstract");
            }

            if (! $reflection_class->isInstantiable()) {
                throw new \Exception("The specified message formatter [$message_formatter] must be instantiatable");
            }

            if (! $reflection_class->implementsInterface(MessageFormatterInterface::class)) {
                throw new \Exception("The specified message formatter [$message_formatter] must implement the interface [".MessageFormatterInterface::class.']');
            }

            $this->app->bind(MessageFormatterInterface::class, $message_formatter);
        }
    }

    private function configurePathGenerator(): void
    {
        $driver = config('db-query-logger.driver');
        $driver_info = config("db-query-logger.drivers.$driver");

        if (isset($driver_info['path'])) {
            $path_generator = $driver_info['path'];

            $reflection_class = new \ReflectionClass($path_generator);

            if ($reflection_class->isAbstract()) {
                throw new \Exception("The specified path generator [$path_generator] must not be abstract");
            }

            if (! $reflection_class->isInstantiable()) {
                throw new \Exception("The specified path generator [$path_generator] must be instantiatable");
            }

            if (! $reflection_class->implementsInterface(PathGeneratorInterface::class)) {
                throw new \Exception("The specified path generator [$path_generator] must implement the interface [".PathGeneratorInterface::class.']');
            }

            if ($reflection_class->isAnonymous()) {
                throw new \Exception("The specified path generator [$path_generator] must not be anonymous");
            }

            $this->app->bind(PathGeneratorInterface::class, $path_generator);
        }
    }
}
